# Generated by Django 4.1.4 on 2022-12-30 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='delete_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
